INSERT INTO TB_ENDERECO (NUMERO, RUA, BAIRRO, CIDADE, UF, COMPLEMENTO, CEP)
VALUES (12345, 'Rua da Paz', 'Iputinga', 'Recife', 'PE', 'Casa', '50740-420');

INSERT INTO TB_INF_SDEMOGRAFICAS (GENERO, COR_RACA, ESTADO_CIVIL, FORMACAO)
VALUES ('Masculino', 'Negro', 'Solteiro', 'Superior Completo');

INSERT INTO TB_CLIENTE (TITULAR, DATA_NASCIMENTO, CPF_CNPJ, CODIGO_TIPO_CLIENTE, ENDERECO_ID, INFORMACOES_ID)
VALUES ('Zacarias', '1988-12-22', '10437135497', 'J', 1, 1);

INSERT INTO TB_CONTA (NUMERO_CONTA, NUMERO_AGENCIA, TITULAR_ID, CODIGO_TIPO_DE_CONTA)
VALUES ('15369-8', '2569-8', 1, 'P');
