CREATE TABLE IF NOT EXISTS TB_ENDERECO(
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    NUMERO INT NOT NULL,
    RUA VARCHAR(50) NOT NULL,
    BAIRRO VARCHAR(50) NOT NULL,
    CIDADE VARCHAR(50) NOT NULL,
    UF VARCHAR(2) NOT NULL,
    COMPLEMENTO VARCHAR(100),
    CEP VARCHAR(9) NOT NULL,
    CONSTRAINT ENDERECO_PK PRIMARY KEY (ID)
);
CREATE TABLE IF NOT EXISTS TB_CLIENTE(
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    TITULAR VARCHAR(50) NOT NULL,
    DATA_NASCIMENTO DATE,
    CPF_CNPJ VARCHAR(18),
    CODIGO_TIPO_CLIENTE CHAR(1),
    ENDERECO_ID INT NOT NULL,
    CONSTRAINT CLIENTE_PK PRIMARY KEY (ID),
    CONSTRAINT ENDERECO_FK FOREIGN KEY (ENDERECO_ID) REFERENCES TB_ENDERECO(ID)
  );

CREATE TABLE IF NOT EXISTS TB_CONTA(
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    NUMERO_CONTA VARCHAR(7) NOT NULL,
    NUMERO_AGENCIA VARCHAR(6) NOT NULL,
    TITULAR_ID INT NOT NULL,
    SALDO_CONTA MONEY,
    CODIGO_TIPO_DE_CONTA VARCHAR(1),
    CONSTRAINT CONTA_PK PRIMARY KEY (ID),
    CONSTRAINT TITULAR_FK FOREIGN KEY (TITULAR_ID) REFERENCES TB_CLIENTE(ID)
);
